/**
 * Hand-curated list of high-authority domains used to seed the sitemap.
 * Search bots crawling these /d/<domain> URLs warm-cache the dossier results
 * and index the pages with real data. No manual content per entry.
 *
 * All entries MUST be lowercase, syntactically valid domains (no scheme, no path).
 * Enforced by tests/unit/lib/seo/popular-domains.test.ts.
 */
export const popularDomains: readonly string[] = [
  // Developer platforms
  "github.com",
  "gitlab.com",
  "bitbucket.org",
  "sourcehut.org",
  "codeberg.org",
  "vercel.com",
  "netlify.com",
  "render.com",
  "railway.app",
  "fly.io",
  "heroku.com",
  "digitalocean.com",
  "linode.com",
  "vultr.com",
  "hetzner.com",
  // Cloud
  "aws.amazon.com",
  "cloud.google.com",
  "azure.microsoft.com",
  "cloudflare.com",
  "fastly.com",
  "akamai.com",
  "bunny.net",
  // Email providers
  "gmail.com",
  "outlook.com",
  "yahoo.com",
  "protonmail.com",
  "icloud.com",
  "fastmail.com",
  "tutanota.com",
  "hey.com",
  "zoho.com",
  // Email infrastructure
  "sendgrid.com",
  "mailchimp.com",
  "mailgun.com",
  "postmarkapp.com",
  "brevo.com",
  "resend.com",
  "amazonses.com",
  "sparkpost.com",
  // Productivity SaaS
  "notion.so",
  "linear.app",
  "figma.com",
  "slack.com",
  "loom.com",
  "miro.com",
  "airtable.com",
  "asana.com",
  "trello.com",
  "basecamp.com",
  "clickup.com",
  "monday.com",
  // Payments
  "stripe.com",
  "paypal.com",
  "square.com",
  "adyen.com",
  "braintreepayments.com",
  "wise.com",
  "revolut.com",
  "payoneer.com",
  "shopify.com",
  "bigcommerce.com",
  // Auth / identity
  "auth0.com",
  "okta.com",
  "onelogin.com",
  "clerk.com",
  "workos.com",
  "supertokens.com",
  "1password.com",
  "bitwarden.com",
  "lastpass.com",
  // Databases / backends
  "mongodb.com",
  "postgresql.org",
  "mysql.com",
  "redis.io",
  "sqlite.org",
  "supabase.com",
  "planetscale.com",
  "neon.tech",
  "cockroachlabs.com",
  "firebase.google.com",
  // Observability
  "datadoghq.com",
  "grafana.com",
  "sentry.io",
  "pagerduty.com",
  "newrelic.com",
  "honeycomb.io",
  "rollbar.com",
  "loggly.com",
  "splunk.com",
  // Analytics / product
  "segment.com",
  "mixpanel.com",
  "amplitude.com",
  "posthog.com",
  "hotjar.com",
  "fullstory.com",
  // CI / build / package
  "circleci.com",
  "travis-ci.com",
  "buildkite.com",
  "semaphoreci.com",
  "npmjs.com",
  "pypi.org",
  "crates.io",
  "packagist.org",
  "rubygems.org",
  "maven.org",
  // AI / ML
  "openai.com",
  "anthropic.com",
  "huggingface.co",
  "replicate.com",
  "cohere.com",
  "mistral.ai",
  "perplexity.ai",
  "elevenlabs.io",
  // Infra / devops tools
  "hashicorp.com",
  "docker.com",
  "kubernetes.io",
  "helm.sh",
  "istio.io",
  "terraform.io",
  "ansible.com",
  // Media / social
  "twitter.com",
  "x.com",
  "instagram.com",
  "facebook.com",
  "linkedin.com",
  "youtube.com",
  "twitch.tv",
  "reddit.com",
  "medium.com",
  "substack.com",
  "mastodon.social",
  "bsky.app",
  "threads.net",
  "tiktok.com",
  "pinterest.com",
  // News / publishing
  "nytimes.com",
  "wsj.com",
  "theguardian.com",
  "bbc.com",
  "cnn.com",
  "reuters.com",
  "bloomberg.com",
  "techcrunch.com",
  "wired.com",
  "arstechnica.com",
  "theverge.com",
  "ycombinator.com",
  "news.ycombinator.com",
  "producthunt.com",
  "stackoverflow.com",
  "dev.to",
  "hashnode.com",
  // Storage / sync
  "dropbox.com",
  "box.com",
  "onedrive.live.com",
  "drive.google.com",
  // Registrars / DNS
  "godaddy.com",
  "namecheap.com",
  "hover.com",
  "porkbun.com",
  "gandi.net",
  "dnsimple.com",
  "route53.amazonaws.com",
  "ns1.com",
  // Commerce / reference
  "amazon.com",
  "ebay.com",
  "walmart.com",
  "target.com",
  "bestbuy.com",
  "apple.com",
  "microsoft.com",
  "google.com",
  "meta.com",
  // Banks / fintech
  "chase.com",
  "bankofamerica.com",
  "wellsfargo.com",
  "citibank.com",
  "hsbc.com",
  "barclays.co.uk",
  "americanexpress.com",
  "capitalone.com",
  "schwab.com",
  "fidelity.com",
  "robinhood.com",
  // Communications
  "zoom.us",
  "teams.microsoft.com",
  "meet.google.com",
  "webex.com",
  "discord.com",
  "telegram.org",
  "signal.org",
  "whatsapp.com",
  // Video / streaming
  "netflix.com",
  "disneyplus.com",
  "hulu.com",
  "primevideo.com",
  "spotify.com",
  "soundcloud.com",
  // CRM / support
  "salesforce.com",
  "hubspot.com",
  "zendesk.com",
  "intercom.com",
  "freshdesk.com",
  "helpscout.com",
  // Website builders
  "webflow.com",
  "squarespace.com",
  "wix.com",
  "wordpress.com",
  "ghost.org",
  // Search / ops
  "algolia.com",
  "meilisearch.com",
  "elastic.co",
  // Telephony
  "twilio.com",
  "vonage.com",
  "plivo.com",
  // Image / media CDN
  "cloudinary.com",
  "imgix.com",
  // Extras
  "gitea.com",
  "forgejo.org",
  "tailscale.com",
  "wireguard.com",
  "openvpn.net",
  "coolify.io",
  "dokploy.com",
  "caprover.com",
  "clerk.dev",
  "frontegg.com",
  "logto.io",
  "better-auth.com",
  "deno.com",
  "bun.sh",
  "astro.build",
  "remix.run",
  "solidjs.com",
  "sveltekit.io",
  "svelte.dev",
  "vitejs.dev",
  "rollupjs.org",
  "esbuild.github.io",
];
